### ISSUE TITLE
site_url() in theme-options.php causes a problem

### ISSUE THREAD

**Issue by barisunver** [BenSibley/Period#1]
Two instances of $customizer_url include the `site_url()` function (first one in **line 12** of `theme-options.php`, second one in **line 157** of Period Pro plugin's `period-pro.php`) causes a small problem of the Customizer opening with the URL that WordPress is installed in (e.g. "example.com/wp/"), and not the homepage (e.g. "example.com").

The solution is simple: Use `home_url()` instead of `site_url()`.

**Comment by BenSibley** [comment]
Ah good catch, thanks!

**Comment by barisunver** [comment]
Don't mention it 👍
